"""
Situations de réglage pré-enregistrées pour l'assistant IA audioprothésiste.
Couvre les environnements sonores quotidiens les plus fréquents.
"""

FITTING_SITUATIONS: list[dict] = [
    # ─── ENVIRONNEMENTS CALMES ────────────────────────────────────────────────
    {
        "key": "domicile_calme",
        "label": "Domicile calme",
        "categorie": "Environnements calmes",
        "description": "Silence relatif à la maison, lecture, détente",
        "niveau_bruit_moyen_db": 35,
        "parametres_sugges": {
            "programme": "Environnement calme",
            "reduction_bruit": "faible",
            "compression": "douce",
            "directivite": "omnidirectionnelle",
        },
        "conseils": "Gain linéaire ou légèrement compressé. Réduction du bruit minimale pour préserver la qualité sonore.",
        "indicateurs_satisfaction": ["confort", "clarté de la voix", "sons naturels"],
    },
    {
        "key": "bureau_calme",
        "label": "Bureau calme",
        "categorie": "Environnements calmes",
        "description": "Travail de bureau peu bruyant, concentration",
        "niveau_bruit_moyen_db": 40,
        "parametres_sugges": {
            "programme": "Bureau",
            "reduction_bruit": "faible",
            "compression": "modérée",
            "directivite": "omnidirectionnelle",
        },
        "conseils": "Amplification modérée, confort auditif prioritaire. Réduire légèrement les fréquences aiguës si fatigue.",
        "indicateurs_satisfaction": ["clarté voix", "confort longue durée", "sons informatiques"],
    },

    # ─── SITUATIONS SOCIALES ──────────────────────────────────────────────────
    {
        "key": "conversation_face_a_face",
        "label": "Conversation en face à face",
        "categorie": "Situations sociales",
        "description": "Dialogue avec une personne dans un endroit calme",
        "niveau_bruit_moyen_db": 45,
        "parametres_sugges": {
            "programme": "Conversation",
            "reduction_bruit": "faible",
            "compression": "modérée",
            "directivite": "directionnelle_douce",
        },
        "conseils": "Optimiser les fréquences 1-3 kHz (intelligibilité de la parole). Activer la directivité adaptative si disponible.",
        "indicateurs_satisfaction": ["intelligibilité", "voix naturelle", "facilité de compréhension"],
    },
    {
        "key": "restaurant",
        "label": "Restaurant / café",
        "categorie": "Situations sociales",
        "description": "Repas en groupe, bruit ambiant fort, reverb",
        "niveau_bruit_moyen_db": 70,
        "parametres_sugges": {
            "programme": "Restaurant",
            "reduction_bruit": "forte",
            "compression": "forte",
            "directivite": "directionnelle_forte",
            "focus_parole": True,
        },
        "conseils": "Directivité forte vers l'avant, réduction bruit agressive, focus sur 500 Hz-4 kHz. Attention à ne pas trop comprimer.",
        "indicateurs_satisfaction": ["compréhension en groupe", "fatigue auditive", "confort en environnement bruyant"],
    },
    {
        "key": "reunion_groupe",
        "label": "Réunion / groupe",
        "categorie": "Situations sociales",
        "description": "Réunion professionnelle ou familiale avec plusieurs interlocuteurs",
        "niveau_bruit_moyen_db": 60,
        "parametres_sugges": {
            "programme": "Réunion",
            "reduction_bruit": "modérée",
            "compression": "modérée",
            "directivite": "directionnelle_adaptative",
        },
        "conseils": "Directivité adaptative pour suivre les interlocuteurs. Réduction bruit modérée pour conserver la spatialisation.",
        "indicateurs_satisfaction": ["suivi des interlocuteurs", "compréhension", "fatigue"],
    },
    {
        "key": "fete_reception",
        "label": "Fête / réception",
        "categorie": "Situations sociales",
        "description": "Ambiance festive très bruyante, musique, nombreuses conversations",
        "niveau_bruit_moyen_db": 80,
        "parametres_sugges": {
            "programme": "Bruit intense",
            "reduction_bruit": "maximale",
            "compression": "forte",
            "directivite": "directionnelle_forte",
        },
        "conseils": "Programme 'bruit intense'. Suggérer au patient de se positionner face à son interlocuteur. Envisager Bluetooth vers smartphone.",
        "indicateurs_satisfaction": ["confort", "compréhension partielle", "non-fatigue"],
    },

    # ─── MÉDIAS ET TECHNOLOGIE ────────────────────────────────────────────────
    {
        "key": "television",
        "label": "Télévision",
        "categorie": "Médias et technologie",
        "description": "Regarder la télévision à distance normale (2-4 m)",
        "niveau_bruit_moyen_db": 55,
        "parametres_sugges": {
            "programme": "TV",
            "reduction_bruit": "modérée",
            "compression": "douce",
            "directivite": "directionnelle_avant",
            "bluetooth_tv": "recommandé",
        },
        "conseils": "Si l'appareil est Bluetooth, jumeler avec un adaptateur TV. Sinon, orienter la directivité vers l'écran. Boost 2-4 kHz.",
        "indicateurs_satisfaction": ["compréhension des dialogues", "volume TV", "sons d'ambiance"],
    },
    {
        "key": "telephone",
        "label": "Téléphone",
        "categorie": "Médias et technologie",
        "description": "Conversation téléphonique (mobile ou fixe)",
        "niveau_bruit_moyen_db": 65,
        "parametres_sugges": {
            "programme": "Téléphone",
            "telecoil": True,
            "streaming_bluetooth": True,
            "reduction_bruit": "forte",
            "directivite": "omnidirectionnelle",
        },
        "conseils": "Activer la bobine téléphonique ou le streaming Bluetooth. Programme dédié téléphone avec réduction bruit maximale.",
        "indicateurs_satisfaction": ["clarté voix téléphone", "facilité d'utilisation", "larsen"],
    },
    {
        "key": "visioconference",
        "label": "Visioconférence / Teams",
        "categorie": "Médias et technologie",
        "description": "Appel vidéo professionnel ou personnel via ordinateur",
        "niveau_bruit_moyen_db": 55,
        "parametres_sugges": {
            "programme": "Streaming",
            "streaming_bluetooth": True,
            "reduction_bruit": "forte",
            "directivite": "directionnelle_micro",
        },
        "conseils": "Streaming direct depuis l'ordinateur via Bluetooth. Vérifier la compatibilité avec l'application.",
        "indicateurs_satisfaction": ["clarté voix", "latence", "qualité streaming"],
    },
    {
        "key": "musique_ecoute",
        "label": "Écoute musicale",
        "categorie": "Médias et technologie",
        "description": "Écoute de musique (radio, streaming, hi-fi)",
        "niveau_bruit_moyen_db": 65,
        "parametres_sugges": {
            "programme": "Musique",
            "reduction_bruit": "minimale",
            "compression": "très_douce",
            "directivite": "omnidirectionnelle",
            "egaliseur": "préserve_basses",
        },
        "conseils": "Programme musique avec compression minimale. Réduction bruit désactivée ou minimale pour préserver la richesse sonore. Bandes larges.",
        "indicateurs_satisfaction": ["richesse sonore", "basses", "aiguës", "naturalité"],
    },
    {
        "key": "musique_pratique",
        "label": "Pratique musicale",
        "categorie": "Médias et technologie",
        "description": "Jouer d'un instrument, chanter, répétition musicale",
        "niveau_bruit_moyen_db": 85,
        "parametres_sugges": {
            "programme": "Musicien",
            "reduction_bruit": "désactivée",
            "compression": "minimale",
            "directivite": "omnidirectionnelle",
            "protection_pic": True,
        },
        "conseils": "Programme musicien spécifique. Gain réduit pour protéger de la saturation. Pas de réduction de bruit. Protection pic si besoin.",
        "indicateurs_satisfaction": ["qualité acoustique instrument", "retour sonore", "saturation"],
    },

    # ─── EXTÉRIEUR / MOBILITÉ ─────────────────────────────────────────────────
    {
        "key": "exterieur_calme",
        "label": "Extérieur calme",
        "categorie": "Extérieur et mobilité",
        "description": "Promenade en forêt, jardin, parc tranquille",
        "niveau_bruit_moyen_db": 45,
        "parametres_sugges": {
            "programme": "Extérieur",
            "reduction_bruit": "faible",
            "filtre_vent": "faible",
            "directivite": "omnidirectionnelle",
        },
        "conseils": "Filtre vent activé à faible niveau. Maintenir les sons environnementaux pour la sécurité (voitures, etc.).",
        "indicateurs_satisfaction": ["sons nature", "voix en extérieur", "bruit vent"],
    },
    {
        "key": "exterieur_bruyant",
        "label": "Extérieur bruyant / rue",
        "categorie": "Extérieur et mobilité",
        "description": "Rue commerçante, marché, zone urbaine animée",
        "niveau_bruit_moyen_db": 72,
        "parametres_sugges": {
            "programme": "Rue",
            "reduction_bruit": "forte",
            "filtre_vent": "modéré",
            "directivite": "directionnelle_forte",
        },
        "conseils": "Réduction bruit forte, filtre vent activé. Directivité avant pour conversations. Alertes sonores préservées pour sécurité.",
        "indicateurs_satisfaction": ["confort", "sécurité piéton", "compréhension"],
    },
    {
        "key": "vent",
        "label": "Vent / intempéries",
        "categorie": "Extérieur et mobilité",
        "description": "Conditions venteuses, pluie, temps agité",
        "niveau_bruit_moyen_db": 75,
        "parametres_sugges": {
            "programme": "Vent",
            "filtre_vent": "maximal",
            "reduction_bruit": "forte",
            "directivite": "directionnelle_forte",
        },
        "conseils": "Filtre vent maximal. Le patient peut temporairement réduire le gain ou passer en mode protection.",
        "indicateurs_satisfaction": ["confort vent", "absence de saturation", "voix malgré vent"],
    },
    {
        "key": "voiture",
        "label": "En voiture",
        "categorie": "Extérieur et mobilité",
        "description": "Conduite automobile, passager, bruit moteur/autoroute",
        "niveau_bruit_moyen_db": 68,
        "parametres_sugges": {
            "programme": "Voiture",
            "reduction_bruit": "forte",
            "compression": "forte",
            "directivite": "directionnelle_adaptative",
        },
        "conseils": "Programme voiture. Directivité adaptative pour converser avec le conducteur/passager. Streaming GPS recommandé si Bluetooth.",
        "indicateurs_satisfaction": ["compréhension GPS/radio", "conversation voiture", "confort bruit moteur"],
    },
    {
        "key": "transports_commun",
        "label": "Transports en commun",
        "categorie": "Extérieur et mobilité",
        "description": "Bus, métro, train, avion",
        "niveau_bruit_moyen_db": 78,
        "parametres_sugges": {
            "programme": "Transport",
            "reduction_bruit": "forte",
            "filtre_vent": "modéré",
            "compression": "forte",
        },
        "conseils": "Bruit impulsionnel fréquent (portes, freins). Programme transport avec bonne gestion des bruits impulsionnels.",
        "indicateurs_satisfaction": ["confort", "annonces sonores", "conversations"],
    },
    {
        "key": "velo_sport",
        "label": "Vélo / sport extérieur",
        "categorie": "Extérieur et mobilité",
        "description": "Activité physique en extérieur, cyclisme, jogging",
        "niveau_bruit_moyen_db": 70,
        "parametres_sugges": {
            "programme": "Sport",
            "filtre_vent": "fort",
            "reduction_bruit": "modérée",
            "directivite": "omnidirectionnelle",
            "securite_alertes": True,
        },
        "conseils": "Filtre vent fort. Alertes sonores (klaxons, voitures) préservées pour sécurité. Gain stable malgré les mouvements.",
        "indicateurs_satisfaction": ["sécurité", "confort vent", "alertes préservées"],
    },

    # ─── LIEUX SPÉCIFIQUES ────────────────────────────────────────────────────
    {
        "key": "supermarche",
        "label": "Supermarché / grande surface",
        "categorie": "Lieux spécifiques",
        "description": "Courses, caisses, rayons bruyants",
        "niveau_bruit_moyen_db": 65,
        "parametres_sugges": {
            "programme": "Grande surface",
            "reduction_bruit": "forte",
            "compression": "forte",
            "directivite": "directionnelle_adaptative",
        },
        "conseils": "Annonces diffusées difficiles à comprendre. Directivité adaptative. Réduction bruit forte.",
        "indicateurs_satisfaction": ["compréhension caissier", "annonces", "confort"],
    },
    {
        "key": "cinema_theatre",
        "label": "Cinéma / Théâtre",
        "categorie": "Lieux spécifiques",
        "description": "Salle de spectacle, acoustique variable",
        "niveau_bruit_moyen_db": 70,
        "parametres_sugges": {
            "programme": "Spectacle",
            "teleloop": "si_disponible",
            "reduction_bruit": "faible",
            "directivite": "directionnelle_avant",
        },
        "conseils": "Vérifier la présence d'une boucle magnétique. Programme spectacle avec directivité scène. Réduction bruit faible.",
        "indicateurs_satisfaction": ["intelligibilité dialogues", "musique naturelle", "confort"],
    },
    {
        "key": "lieu_culte",
        "label": "Lieu de culte / conférence",
        "categorie": "Lieux spécifiques",
        "description": "Église, mosquée, salle de conférence avec forte réverbération",
        "niveau_bruit_moyen_db": 55,
        "parametres_sugges": {
            "programme": "Réverbération",
            "reduction_bruit": "modérée",
            "teleloop": "si_disponible",
            "directivite": "directionnelle_avant",
            "anti_reverb": True,
        },
        "conseils": "La réverbération est le principal défi. Activer la gestion de reverb si disponible. Boucle magnétique souvent présente.",
        "indicateurs_satisfaction": ["intelligibilité discours", "echo", "confort"],
    },
    {
        "key": "piscine_salle_sport",
        "label": "Piscine / salle de sport",
        "categorie": "Lieux spécifiques",
        "description": "Environnement très réverbérant, bruyant",
        "niveau_bruit_moyen_db": 75,
        "parametres_sugges": {
            "programme": "Sport intérieur",
            "reduction_bruit": "forte",
            "anti_reverb": True,
            "directivite": "directionnelle_forte",
        },
        "conseils": "Forte réverbération + fort bruit. Attention à l'humidité (IP54 minimum recommandé). Programme sport intérieur.",
        "indicateurs_satisfaction": ["confort", "humidité", "compréhension consignes"],
    },
    {
        "key": "cuisine",
        "label": "Cuisine / bruits ménagers",
        "categorie": "Lieux spécifiques",
        "description": "Bruits de vaisselle, hotte, lave-vaisselle, bruits impulsionnels",
        "niveau_bruit_moyen_db": 65,
        "parametres_sugges": {
            "programme": "Bruits maison",
            "reduction_bruit": "modérée",
            "gestion_impulsionnel": True,
            "compression": "forte",
        },
        "conseils": "Bruits impulsionnels fréquents (couverts, casseroles). Activer la gestion des bruits impulsionnels.",
        "indicateurs_satisfaction": ["confort bruits brusques", "compréhension voix", "non-saturation"],
    },

    # ─── SITUATIONS PROFESSIONNELLES ──────────────────────────────────────────
    {
        "key": "conference_amphi",
        "label": "Conférence / amphi",
        "categorie": "Situations professionnelles",
        "description": "Grande salle, orateur éloigné, micro amplifié",
        "niveau_bruit_moyen_db": 60,
        "parametres_sugges": {
            "programme": "Conférence",
            "directivite": "directionnelle_forte",
            "reduction_bruit": "modérée",
            "boost_parole": True,
        },
        "conseils": "Micro-émetteur recommandé si disponible. Directivité très forte vers l'orateur. Boost intelligibilité parole.",
        "indicateurs_satisfaction": ["intelligibilité orateur", "distance", "fatigabilité"],
    },
    {
        "key": "chantier_industrie",
        "label": "Environnement industriel / chantier",
        "categorie": "Situations professionnelles",
        "description": "Bruits forts et continus, machinerie, protection auditive",
        "niveau_bruit_moyen_db": 90,
        "parametres_sugges": {
            "programme": "Protection",
            "limitation_sortie": True,
            "reduction_bruit": "maximale",
            "compression": "forte",
        },
        "conseils": "Programme protection. Limiter la sortie maximale (MPO) pour protéger le résidu auditif. Port de protections sur-auriculaires recommandé.",
        "indicateurs_satisfaction": ["protection", "communication avec collègues", "alertes sécurité"],
    },
    {
        "key": "enseignement",
        "label": "Enseignement / classe",
        "categorie": "Situations professionnelles",
        "description": "Enseignant ou élève en classe, acoustique scolaire",
        "niveau_bruit_moyen_db": 65,
        "parametres_sugges": {
            "programme": "Classe",
            "directivite": "directionnelle_adaptative",
            "reduction_bruit": "forte",
            "systeme_fm": "recommandé",
        },
        "conseils": "Système FM/Roger recommandé en classe. Directivité adaptative. Envisager un micro-émetteur pour l'enseignant.",
        "indicateurs_satisfaction": ["compréhension enseignant", "participation", "fatigue journée"],
    },

    # ─── SITUATIONS SPÉCIALES ─────────────────────────────────────────────────
    {
        "key": "sommeil_repos",
        "label": "Repos / nuit (sans appareils)",
        "categorie": "Situations spéciales",
        "description": "Conseils pour la nuit sans appareils",
        "niveau_bruit_moyen_db": 30,
        "parametres_sugges": {},
        "conseils": "Les appareils ne se portent pas la nuit. Conseiller une alarme lumineuse ou vibrante. Alerte incendie adaptée aux malentendants.",
        "indicateurs_satisfaction": ["sécurité nocturne", "confort", "réveil"],
    },
    {
        "key": "eau_douche",
        "label": "Proximité eau / douche",
        "categorie": "Situations spéciales",
        "description": "Gestion des appareils autour de l'eau",
        "niveau_bruit_moyen_db": 65,
        "parametres_sugges": {
            "indice_ip": "IP68_recommandé",
        },
        "conseils": "Vérifier l'indice IP de l'appareil. IP68 : peut être porté sous la douche. IP67 : résiste aux projections. Retrait recommandé si < IP54.",
        "indicateurs_satisfaction": ["protection eau", "durabilité", "confiance patient"],
    },
    {
        "key": "telephone_portable_bluetooth",
        "label": "Couplage Bluetooth smartphone",
        "categorie": "Situations spéciales",
        "description": "Association et usage Bluetooth avec smartphone",
        "niveau_bruit_moyen_db": 60,
        "parametres_sugges": {
            "streaming_bluetooth": True,
            "programme_streaming": "Bluetooth",
            "reduction_bruit": "forte",
        },
        "conseils": "Vérifier la compatibilité iOS/Android. Guide le patient pour le jumelage. Tester les applications du fabricant (Phonak app, ReSound app, etc.).",
        "indicateurs_satisfaction": ["facilité couplage", "qualité streaming", "autonomie batterie"],
    },
    {
        "key": "ipa_assistant_vocal",
        "label": "Assistant vocal (Siri, Google...)",
        "categorie": "Situations spéciales",
        "description": "Utilisation des assistants vocaux via l'appareil auditif",
        "niveau_bruit_moyen_db": 50,
        "parametres_sugges": {
            "streaming_bluetooth": True,
            "assistant_vocal": True,
        },
        "conseils": "Fonctionnalité disponible sur certains modèles haut de gamme. Activer dans l'app du fabricant. Tester la reconnaissance vocale.",
        "indicateurs_satisfaction": ["reconnaissance vocale", "facilité utilisation", "autonomie"],
    },

    # ─── MUSIQUE ET SPECTACLE ─────────────────────────────────────────────────
    {
        "key": "concert_spectacle",
        "label": "Concert / spectacle vivant",
        "categorie": "Musique et spectacle",
        "description": "Salle de concert, musique amplifiée, niveau élevé",
        "niveau_bruit_moyen_db": 95,
        "parametres_sugges": {
            "programme": "Musique live",
            "reduction_bruit": "minimale",
            "compression": "douce",
            "limitation_sortie": True,
        },
        "conseils": "Programme musique dédié. Compression douce pour préserver la dynamique. Protection auditive recommandée si > 100 dB.",
        "indicateurs_satisfaction": ["richesse musicale", "protection", "confort longue durée"],
    },
    {
        "key": "musique_casque",
        "label": "Écoute musique (casque / streaming)",
        "categorie": "Musique et spectacle",
        "description": "Musique en streaming via Bluetooth ou câble",
        "niveau_bruit_moyen_db": 70,
        "parametres_sugges": {
            "programme": "Streaming musique",
            "streaming_bluetooth": True,
            "compression": "douce",
            "reduction_bruit": "minimale",
        },
        "conseils": "Activer le programme streaming musique. Compression douce pour la dynamique musicale. Vérifier l'appli du fabricant.",
        "indicateurs_satisfaction": ["qualité musicale", "basses", "aigus", "connectivité"],
    },
    {
        "key": "home_cinema",
        "label": "Télévision HD / home cinéma",
        "categorie": "Musique et spectacle",
        "description": "TV avec streamer ou Bluetooth, films et séries",
        "niveau_bruit_moyen_db": 65,
        "parametres_sugges": {
            "programme": "TV",
            "streaming_bluetooth": True,
            "reduction_bruit": "faible",
            "boost_parole": True,
        },
        "conseils": "Utiliser un streamer TV dédié (ex: Phonak TV Connector). Boost parole pour les dialogues. Volume TV peut être réduit pour l'entourage.",
        "indicateurs_satisfaction": ["intelligibilité dialogues", "effets sonores", "indépendance volume"],
    },
    {
        "key": "podcasts_livres_audio",
        "label": "Podcasts / livres audio",
        "categorie": "Musique et spectacle",
        "description": "Contenu audio longue durée, voix seule",
        "niveau_bruit_moyen_db": 55,
        "parametres_sugges": {
            "programme": "Streaming parole",
            "streaming_bluetooth": True,
            "boost_parole": True,
            "reduction_bruit": "faible",
        },
        "conseils": "Programme dédié parole streaming. Boost intelligibilité voix humaine. Autonomie batterie à surveiller.",
        "indicateurs_satisfaction": ["clarté voix", "autonomie", "fatigue auditive"],
    },

    # ─── SPORT ET ACTIVITÉ ────────────────────────────────────────────────────
    {
        "key": "gym_salle_sport",
        "label": "Salle de sport / musculation",
        "categorie": "Sport et activité",
        "description": "Salle de gym bruyante, musique forte, machines",
        "niveau_bruit_moyen_db": 85,
        "parametres_sugges": {
            "programme": "Sport",
            "reduction_bruit": "forte",
            "compression": "forte",
            "indice_ip": "IP54_minimum",
        },
        "conseils": "Programme sport avec réduction bruit renforcée. Vérifier l'IP (transpiration). Certains patients préfèrent retirer les appareils.",
        "indicateurs_satisfaction": ["confort bruit", "tenue physique", "protection transpiration"],
    },
    {
        "key": "course_velo_vent",
        "label": "Course à pied / vélo (vent)",
        "categorie": "Sport et activité",
        "description": "Bruit de vent dominant lors d'activités en extérieur",
        "niveau_bruit_moyen_db": 75,
        "parametres_sugges": {
            "programme": "Extérieur vent sport",
            "reduction_vent": True,
            "directivite": "omnidirectionnelle",
            "compression": "modérée",
        },
        "conseils": "Activer la réduction de vent. Directivité omnidirectionnelle pour la sécurité (entendre la circulation). Indice IP important.",
        "indicateurs_satisfaction": ["réduction vent", "sécurité trafic", "confort sportif"],
    },
    {
        "key": "sport_collectif",
        "label": "Sport collectif (foot, tennis, basket)",
        "categorie": "Sport et activité",
        "description": "Sport en équipe, communication rapide, bruit variable",
        "niveau_bruit_moyen_db": 70,
        "parametres_sugges": {
            "programme": "Sport collectif",
            "directivite": "omnidirectionnelle",
            "reduction_bruit": "modérée",
        },
        "conseils": "Omnidirectionnel pour entendre les coéquipiers de tous côtés. Bandeau ou attaches recommandés. Vérifier l'IP.",
        "indicateurs_satisfaction": ["communication équipe", "sécurité", "maintien en place"],
    },

    # ─── SITUATIONS DIFFICILES ────────────────────────────────────────────────
    {
        "key": "acouphenes_tinnitus",
        "label": "Acouphènes / tinnitus intenses",
        "categorie": "Situations difficiles",
        "description": "Sifflements, bourdonnements persistants gênants",
        "niveau_bruit_moyen_db": 30,
        "parametres_sugges": {
            "programme": "Tinnitus masking",
            "generateur_bruit": True,
            "compression": "douce",
            "reduction_bruit": "minimale",
        },
        "conseils": "Activer le générateur de bruit de masquage (bruit blanc, rose ou fractal selon préférence). Thérapie sonore TRT. Orientation psychologue si nécessaire.",
        "indicateurs_satisfaction": ["atténuation sifflements", "sommeil", "concentration", "anxiété"],
    },
    {
        "key": "hyperacousie",
        "label": "Hyperacousie (tolérance réduite)",
        "categorie": "Situations difficiles",
        "description": "Douleur ou gêne intense aux sons ordinaires",
        "niveau_bruit_moyen_db": 50,
        "parametres_sugges": {
            "programme": "Désensibilisation",
            "reduction_bruit": "faible",
            "compression": "forte",
            "limitation_sortie": True,
            "generateur_bruit": "faible_niveau",
        },
        "conseils": "Protocole de désensibilisation progressive. MPO réduit. Éviter la sur-protection (aggrave l'hyperacousie). Orientation ORL/psy.",
        "indicateurs_satisfaction": ["tolérance sons", "douleur", "qualité de vie"],
    },
    {
        "key": "pluie_humidite",
        "label": "Pluie / forte humidité",
        "categorie": "Situations difficiles",
        "description": "Bruit de pluie masquant, humidité pour les appareils",
        "niveau_bruit_moyen_db": 70,
        "parametres_sugges": {
            "programme": "Extérieur pluie",
            "reduction_bruit": "forte",
            "indice_ip": "IP68_recommandé",
        },
        "conseils": "Vérifier l'IP de l'appareil. Séchage régulier recommandé (boîte séchante UV). Réduction bruit importante pour masquer la pluie.",
        "indicateurs_satisfaction": ["intelligibilité sous pluie", "durabilité", "protection eau"],
    },
    {
        "key": "recrutement_distorsion",
        "label": "Recrutement / distorsion sonore",
        "categorie": "Situations difficiles",
        "description": "Sons déformés, saturation douloureuse à forte intensité",
        "niveau_bruit_moyen_db": 60,
        "parametres_sugges": {
            "programme": "Anti-recrutement",
            "compression": "forte",
            "limitation_sortie": True,
            "ratio_compression": "élevé",
        },
        "conseils": "Compression forte avec ratio élevé (WDRC). Réduire le MPO. Knee point adapté au seuil d'inconfort. Contrôler avec UCL test.",
        "indicateurs_satisfaction": ["confort sons forts", "distorsion", "saturation"],
    },
    {
        "key": "premiers_jours_appareillage",
        "label": "Premiers jours d'appareillage",
        "categorie": "Situations difficiles",
        "description": "Adaptation initiale, sons paraissent forts et inhabituels",
        "niveau_bruit_moyen_db": 50,
        "parametres_sugges": {
            "programme": "Démarrage doux",
            "gain_initial": "réduit_80pct",
            "compression": "forte",
            "reduction_bruit": "modérée",
        },
        "conseils": "Gain initial à 80% de la cible. Augmenter progressivement sur 4-6 semaines. Rassurer sur la normalité de la fatigue auditive initiale.",
        "indicateurs_satisfaction": ["acceptation", "fatigue", "confort global", "motivation"],
    },
    {
        "key": "fatigue_auditive",
        "label": "Fatigue auditive en fin de journée",
        "categorie": "Situations difficiles",
        "description": "Lassitude auditive après journée intense, envie de retirer les appareils",
        "niveau_bruit_moyen_db": 40,
        "parametres_sugges": {
            "programme": "Repos auditif",
            "reduction_bruit": "forte",
            "gain_global": "réduit",
            "compression": "forte",
        },
        "conseils": "Programme de confort pour fin de journée. Réduire le gain global. Autoriser les pauses (30 min sans appareils). Vérifier les embouts si pression.",
        "indicateurs_satisfaction": ["durée port quotidien", "confort embouts", "récupération"],
    },

    # ─── SITUATIONS ÉMOTIONNELLES ─────────────────────────────────────────────
    {
        "key": "anxiete_appareils",
        "label": "Anxiété liée aux appareils",
        "categorie": "Situations émotionnelles",
        "description": "Gêne psychologique, honte, refus de porter en public",
        "niveau_bruit_moyen_db": 45,
        "parametres_sugges": {},
        "conseils": "Écoute active et bienveillante. Valoriser les bénéfices discrets (appareils invisibles). Groupes de parole. Suivi psychologique si besoin. Ne pas forcer.",
        "indicateurs_satisfaction": ["acceptation sociale", "confiance en soi", "port en public"],
    },
    {
        "key": "bureau_open_space",
        "label": "Open-space / plateau de travail",
        "categorie": "Situations professionnelles",
        "description": "Bureaux paysagés, conversations multiples simultanées",
        "niveau_bruit_moyen_db": 65,
        "parametres_sugges": {
            "programme": "Open-space",
            "directivite": "directionnelle_adaptative",
            "reduction_bruit": "forte",
            "boost_parole": True,
        },
        "conseils": "Directivité adaptative pour se concentrer sur l'interlocuteur face à soi. Réduction bruit importante. Micros déportés recommandés.",
        "indicateurs_satisfaction": ["focus interlocuteur", "fatigue cognitive", "compréhension en réunion"],
    },
    {
        "key": "reunion_presentiel",
        "label": "Réunion en présentiel (salle)",
        "categorie": "Situations professionnelles",
        "description": "Table de réunion, plusieurs interlocuteurs autour",
        "niveau_bruit_moyen_db": 58,
        "parametres_sugges": {
            "programme": "Réunion",
            "directivite": "omnidirectionnelle",
            "reduction_bruit": "modérée",
            "boost_parole": True,
        },
        "conseils": "Mode omnidirectionnel pour capter les voix autour de la table. Micro Roger Table recommandé. S'asseoir face aux interlocuteurs principaux.",
        "indicateurs_satisfaction": ["participation réunion", "compréhension tous côtés", "prise de parole"],
    },
    {
        "key": "restaurant_gastronomique",
        "label": "Restaurant gastronomique / soirée",
        "categorie": "Situations sociales",
        "description": "Restaurant chic, bruit de fond modéré, conversation intime",
        "niveau_bruit_moyen_db": 68,
        "parametres_sugges": {
            "programme": "Restaurant",
            "directivite": "directionnelle_forte",
            "reduction_bruit": "forte",
            "boost_parole": True,
        },
        "conseils": "Directivité forte vers le convive face à soi. Réduction bruit maximale. S'installer dos au mur, loin de la cuisine et de la musique.",
        "indicateurs_satisfaction": ["compréhension convive", "confort ambiance", "participation conversation"],
    },
]

SITUATIONS_BY_KEY: dict[str, dict] = {s["key"]: s for s in FITTING_SITUATIONS}
SITUATIONS_BY_CATEGORY: dict[str, list[dict]] = {}
for s in FITTING_SITUATIONS:
    cat = s["categorie"]
    SITUATIONS_BY_CATEGORY.setdefault(cat, []).append(s)
